drop table if exists order_items;
drop table if exists phones;
drop table if exists orders;

create table phones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)  primary key,
  model varchar(254)  not null,
  color VARCHAR (50) NOT  NULL,
  displaySize SMALLINT NOT NULL,
  width SMALLINT,
  length SMALLINT,
  price INT not null
);

create table orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) primary key,
  delivery_price INT not null,

  first_name varchar(100) not null,
  last_name varchar(100) not null,
  delivery_address VARCHAR(250) not null,
  contact_phone_no VARCHAR(250) not null

);

create table order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)  primary key,
  phone_id BIGINT not null,
  order_id BIGINT not null,
  quantity SMALLINT not null,
  foreign key (phone_id) references phones(id),
  foreign key (order_id) references orders(id)
);

CREATE UNIQUE INDEX phones
  ON phones(model);

COMMIT 





